
name: dlma
channels:
  - huggingface
  - pytorch
  - nvidia/label/cuda-11.8.0
  - defaults
  - conda-forge
dependencies:
  - python = 3.11
  - pip

  - pytorch::pytorch >= 2.0
  - pytorch::pytorch-mutex =*=*cuda*
  - transformers >= 4.34
  - datasets
  - tokenizers >= 0.13.3
  - sentencepiece
  - tensorboard
  - wandb
  - pip:
      - accelerate
      - deepspeed
      - ipykernel==6.23.1
      - numpy==1.24.3
      - tqdm==4.65.0
      - beautifulsoup4==4.12.2
      - wandb==0.15.3
      - hydra-core==1.3.2
      - tensor-parallel==1.2.4
      - openai==0.28
      - bs4
      - scikit-learn
      - ipdb
      - Cython
      - homoglyphs
      - trl==0.8.1
      - nltk
      - gradio


  - nvidia/label/cuda-11.8.0::cuda-toolkit = 11.8

  - optree
  - scipy
  - nvitop
  - matplotlib-base
  - rich
  - tqdm
  - typing-extensions